[package]
name = "planorama"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
autotests = false

[profile.test]
opt-level = 1
debug-assertions = true
overflow-checks = true

[[test]]
name = "cli"
path = "tests/integration/cli.rs"

[[test]]
name = "terraform_plan"
path = "tests/integration/terraform_plan.rs"

[[test]]
name = "rendering"
path = "tests/integration/rendering.rs"

[dependencies]
same-file = "1.0.6"
serde_json = "1"

[build-dependencies]
roxmltree = "0.21.1"

[dev-dependencies]
roxmltree = "0.21.1"

[[test]]
name = "large_example"
path = "tests/integration/large_example.rs"
