name: Cargo fmt

on:
  pull_request:
    paths:
      - '**.rs'
      - rust-toolchain.toml
      - .github/workflows/cargo_fmt.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install pinned toolchain
        run: rustc --version --verbose
      - run: cargo fmt --all --check
