name: Cargo test

on:
  push:
    branches: [main]
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - .cargo/**
      - assets/**
      - tests/fixtures/**
      - examples/**
      - .github/workflows/cargo_test.yml
  pull_request:
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - .cargo/**
      - assets/**
      - tests/fixtures/**
      - examples/**
      - .github/workflows/cargo_test.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install pinned toolchain
        run: rustc --version --verbose
      - uses: Swatinem/rust-cache@v2.9.2
        with:
          key: ${{ hashFiles('build.rs', 'assets/**') }}
          cache-workspace-crates: 'true'
      - name: Compile tests
        run: cargo test --locked --all-targets --all-features --no-run
      - name: Run tests
        run: cargo test --locked --all-targets --all-features
